spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          gitlab:
            client-id: ${GITLAB_CLIENT_ID}
            client-secret: ${GITLAB_CLIENT_SECRET}

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

#docker run --name final-project-container final-project \
#  -e DB_PASSWORD='JiraRush' \
#  -e DB_USERNAME='jira' \
#  -e GITHUB_CLIENT_ID='3d0d8738e65881fff266' \
#  -e GITHUB_CLIENT_SECRET='0f97031ce6178b7dfb67a6af587f37e222a16120' \
#  -e GOOGLE_CLIENT_ID='329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com' \
#  -e GOOGLE_CLIENT_SECRET='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' \
#  -e MAIL_PASSWORD='zdfzsrqvgimldzyj' \
#  -e MAIL_USERNAME='jira4jr@gmail.com'

# -Dspring.profiles.active=docker


# docker build -t final-project .
# docker run -d -p 8081:8080 -e DB_PASSWORD='JiraRush' -e DB_USERNAME='jira' -e GITHUB_CLIENT_ID='3d0d8738e65881fff266' -e GITHUB_CLIENT_SECRET='0f97031ce6178b7dfb67a6af587f37e222a16120' -e GOOGLE_CLIENT_ID='329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com' -e GOOGLE_CLIENT_SECRET='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' -e MAIL_PASSWORD='zdfzsrqvgimldzyj' -e MAIL_USERNAME='jira4jr@gmail.com' -e SPRING_PROFILES_ACTIVE='docker' --name final-project-container final-project